#!/bin/bash

# requires bash 4.2 or later

# located at /home/mepley/Work/marketing/demos/openshift/jbds-workspace/openshift-demo-simple/

[[ -v CONFIGURATION_COMPLETED ]] && echo "Using preloaded configuration" && { return || exit ; }

DEMO_TARGET_OPENSHIFT_INSTANCES=(local rhsademo)
DEMO_TARGET_OPENSHIFT_INSTANCE=rhsademo

. config-demo-target-${DEMO_TARGET_OPENSHIFT_INSTANCE}.sh

if [[ -v OPENSHIFT_RHSADEMO_USER_PASSWORD_DEFAULT ]] ; then
	echo "--> Using RHSADEMO password for openshift"
	OPENSHIFT_USER_PRIMARY_PASSWORD_DEFAULT=$OPENSHIFT_RHSADEMO_USER_PASSWORD_DEFAULT
else
	[[ ! -v OPENSHIFT_USER_PRIMARY_PASSWORD_DEFAULT ]] && echo "Please set OPENSHIFT_USER_PRIMARY_PASSWORD_DEFAULT to your openshift password" && exit 1
fi

OPENSHIFT_DOMAIN_LOCALHOST=`hostname`
OPENSHIFT_DOMAIN_RHSADEMO=rhsademo.net
OPENSHIFT_DOMAINS=(${OPENSHIFT_DOMAIN_RHSADEMO} ${OPENSHIFT_DOMAIN_LOCAL})
OPENSHIFT_DOMAIN_DEFAULT=${OPENSHIFT_DOMAINS[0]}
OPENSHIFT_DOMAIN_DEFAULT=${OPENSHIFT_DOMAIN_RHSADEMO}
OPENSHIFT_DOMAIN=${OPENSHIFT_DOMAIN_DEFAULT}

OPENSHIFT_PRIMARY_MASTER_DEFAULT=master.${OPENSHIFT_DOMAIN}
OPENSHIFT_PRIMARY_MASTER=$OPENSHIFT_PRIMARY_MASTER_DEFAULT
OPENSHIFT_PRIMARY_MASTER_PORT_HTTPS=443

OPENSHIFT_PRIMARY_PROXY_AUTH_DEFAULT=proxy.${OPENSHIFT_DOMAIN}
OPENSHIFT_PRIMARY_PROXY_AUTH=${OPENSHIFT_PRIMARY_PROXY_AUTH_DEFAULT}

OPENSHIFT_PRIMARY_APPS_DEFAULT=apps.${OPENSHIFT_DOMAIN}
OPENSHIFT_PRIMARY_APPS=${OPENSHIFT_PRIMARY_APPS_DEFAULT}

OPENSHIFT_PRIMARY_AUTH_METHODS=(password kerberos token cert)
OPENSHIFT_PRIMARY_AUTH_METHOD_CLI_DEFAULT=${OPENSHIFT_PRIMARY_AUTH_METHODS[2]}
OPENSHIFT_PRIMARY_AUTH_METHOD_WEB_DEFAULT=${OPENSHIFT_PRIMARY_AUTH_METHODS[0]}
OPENSHIFT_PRIMARY_AUTH_METHOD_DEFAULT=${OPENSHIFT_PRIMARY_AUTH_METHOD_CLI_DEFAULT}

OPENSHIFT_USER_PRIMARY_DEFAULT=mepley
OPENSHIFT_USER_PRIMARY=${OPENSHIFT_USER_PRIMARY_DEFAULT}
OPENSHIFT_USER_PRIMARY_PASSWORD=${OPENSHIFT_USER_PRIMARY_PASSWORD_DEFAULT}

OPENSHIFT_PRIMARY_CEREDENTIALS_CLI_DEFAULT=
OPENSHIFT_PRIMARY_PROJECT_AMQ_DEFAULT=${OPENSHIFT_USER_PRIMARY_DEFAULT}-fuse-amq
OPENSHIFT_PRIMARY_PROJECT_MYSQLPHP_DEFAULT=${OPENSHIFT_USER_PRIMARY_DEFAULT}-myphp
OPENSHIFT_PRIMARY_PROJECT_JDVDEMO_DEFAULT=${OPENSHIFT_USER_PRIMARY_DEFAULT}-jdvdemo
OPENSHIFT_PRIMARY_PROJECT_DEFAULT=${OPENSHIFT_PRIMARY_PROJECT_JDVDEMO_DEFAULT}
OPENSHIFT_PRIMARY_PROJECT=${OPENSHIFT_PRIMARY_PROJECT_DEFAULT}

# default coordinates for interacting with openshift
OPENSHIFT_USER=${OPENSHIFT_USER_PRIMARY}
OPENSHIFT_PASSWORD=${OPENSHIFT_USER_PRIMARY_PASSWORD}
OPENSHIFT_PROJECT=${OPENSHIFT_PRIMARY_PROJECT}


OPENSHIFT_APPLICATION_NAME_AMQ_BROKER_DEFAULT=broker
OPENSHIFT_APPLICATION_NAME_MYSQLPHP_DEFAULT=myphp
OPENSHIFT_APPLICATION_NAME_JDVDEMO_DEFAULT=jdvdemo
OPENSHIFT_APPLICATION_NAME_DEFAULT=${OPENSHIFT_APPLICATION_NAME_JDVDEMO_DEFAULT}
OPENSHIFT_APPLICATION_NAME=${OPENSHIFT_APPLICATION_NAME_DEFAULT}

# each user entry is an array of (username, password, primary project, and any other projects)
OPENSHIFT_USER_RHSADEMO_MEPLEY=(mepley ${OPENSHIFT_USER_PRIMARY_PASSWORD_DEFAULT} mepley-jdvdemo)
OPENSHIFT_USER_RHSADEMO_MEPLEY2=(mepley2 ${OPENSHIFT_USER_PRIMARY_PASSWORD_DEFAULT} mepley2-jdvdemo)
OPENSHIFT_USER_RHSADEMO_MEPLEY_DEV=(mepley ${OPENSHIFT_USER_PRIMARY_PASSWORD_DEFAULT} mepley-development)
OPENSHIFT_USER_RHSADEMO_MEPLEY_TEST=(mepley ${OPENSHIFT_USER_PRIMARY_PASSWORD_DEFAULT} mepley-testing)
OPENSHIFT_USER_RHSADEMO_MEPLEY_PROD=(mepley ${OPENSHIFT_USER_PRIMARY_PASSWORD_DEFAULT} mepley-production)
OPENSHIFT_USERS_RHSADEMO=(OPENSHIFT_USER_RHSADEMO_MEPLEY OPENSHIFT_USER_RHSADEMO_MEPLEY2 OPENSHIFT_USER_RHSADEMO_MEPLEY_DEV OPENSHIFT_USER_RHSADEMO_MEPLEY_TEST OPENSHIFT_USER_RHSADEMO_MEPLEY_PROD)

OPENSHIFT_OUTPUT_FORMATS=(json yaml)
OPENSHIFT_OUTPUT_FORMAT_DEFAULT=${OPENSHIFT_OUTPUT_FORMATS[0]}

GITHUB_USER_PRIMARY=michaelepley
SCRIPT_ENCRYPTION_KEY=${OPENSHIFT_USER_PRIMARY_PASSWORD}

[[ -v GITHUB_AUTHORIZATION_TOKEN_OPENSHIFT_DEMO_PLAINTEXT ]] || [[ -v GITHUB_AUTHORIZATION_TOKEN_OPENSHIFT_DEMO_CIPHERTEXT ]] || { echo "FAILED: GITHUB_AUTHORIZATION_TOKEN_OPENSHIFT_DEMO_PLAINTEXT must be set and match a valid GitHub.com Oauth2 personal access token with the following roles:" ; }
#GITHUB_AUTHORIZATION_TOKEN_OPENSHIFT_DEMO_PLAINTEXT=`echo ${GITHUB_AUTHORIZATION_TOKEN_OPENSHIFT_DEMO_CIPHERTEXT} | openssl enc -d -a | openssl enc -d -aes-256-cbc -k ${SCRIPT_ENCRYPTION_KEY} `
[[ -v GITHUB_AUTHORIZATION_TOKEN_OPENSHIFT_DEMO_PLAINTEXT ]] && echo "--> it is recommended to use an encrypted token; you may encrypt and store the token using the following: " && echo ' GITHUB_AUTHORIZATION_TOKEN_OPENSHIFT_DEMO_CIPHERTEXT=`echo ${GITHUB_AUTHORIZATION_TOKEN_OPENSHIFT_DEMO_PLAINTEXT} | openssl enc -e -aes-256-cbc -k ${SCRIPT_ENCRYPTION_KEY} | openssl enc -e -a`'
: ${GITHUB_AUTHORIZATION_TOKEN_OPENSHIFT_DEMO_PLAINTEXT:-`echo ${GITHUB_AUTHORIZATION_TOKEN_OPENSHIFT_DEMO_CIPHERTEXT} | openssl enc -d -a | openssl enc -d -aes-256-cbc -k ${SCRIPT_ENCRYPTION_KEY}`} || { echo "FAILED: Could not validate the github token" && exit 1; }

echo "Configuration_______________________________________________"
echo "DEMO_TARGET_OPENSHIFT_INSTANCE          = ${DEMO_TARGET_OPENSHIFT_INSTANCE}"
echo "OPENSHIFT_DOMAIN_DEFAULT                = ${OPENSHIFT_DOMAIN_DEFAULT}"
echo "OPENSHIFT_DOMAIN                        = ${OPENSHIFT_DOMAIN}"
echo "OPENSHIFT_PRIMARY_MASTER_DEFAULT        = ${OPENSHIFT_PRIMARY_MASTER_DEFAULT}"
echo "OPENSHIFT_PRIMARY_MASTER                = ${OPENSHIFT_PRIMARY_MASTER}"
echo "OPENSHIFT_PRIMARY_APPS_DEFAULT          = ${OPENSHIFT_PRIMARY_APPS_DEFAULT}"
echo "OPENSHIFT_PRIMARY_APPS                  = ${OPENSHIFT_PRIMARY_APPS}"
echo "OPENSHIFT_USER_PRIMARY_DEFAULT          = ${OPENSHIFT_USER_PRIMARY_DEFAULT}"
echo "OPENSHIFT_USER_PRIMARY                  = ${OPENSHIFT_USER_PRIMARY}"
echo "OPENSHIFT_USER_PRIMARY_PASSWORD_DEFAULT = `echo ${OPENSHIFT_USER_PRIMARY_PASSWORD_DEFAULT} | md5sum` (obfuscated)"
echo "OPENSHIFT_USER_PRIMARY_PASSWORD         = `echo ${OPENSHIFT_USER_PRIMARY_PASSWORD} | md5sum` (obfuscated)"
echo "OPENSHIFT_PRIMARY_PROJECT_AMQ_DEFAULT   = ${OPENSHIFT_PRIMARY_PROJECT_AMQ_DEFAULT}"
echo "OPENSHIFT_PRIMARY_PROJECT_MYSQLPHP_DEFAULT   = ${OPENSHIFT_PRIMARY_PROJECT_MYSQLPHP_DEFAULT}"
echo "OPENSHIFT_PRIMARY_PROJECT_DEFAULT       = ${OPENSHIFT_PRIMARY_PROJECT_DEFAULT}"
echo "OPENSHIFT_PRIMARY_PROJECT               = ${OPENSHIFT_PRIMARY_PROJECT}"
echo "OPENSHIFT_APPLICATION_NAME_AMQ_BROKER_DEFAULT = ${OPENSHIFT_APPLICATION_NAME_AMQ_BROKER_DEFAULT}"
echo "OPENSHIFT_APPLICATION_NAME_MYSQLPHP_DEFAULT = ${OPENSHIFT_APPLICATION_NAME_MYSQLPHP_DEFAULT}"
echo "OPENSHIFT_APPLICATION_NAME_DEFAULT      = ${OPENSHIFT_APPLICATION_NAME_DEFAULT}"
echo "OPENSHIFT_APPLICATION_NAME              = ${OPENSHIFT_APPLICATION_NAME}"
echo "OPENSHIFT_OUTPUT_FORMATS                = ${OPENSHIFT_OUTPUT_FORMATS[*]}"
echo "OPENSHIFT_OUTPUT_FORMAT_DEFAULT         = ${OPENSHIFT_OUTPUT_FORMAT_DEFAULT}"
echo ""
echo "GITHUB_USER_PRIMARY                     = ${GITHUB_USER_PRIMARY}"
echo "OPENSHIFT_USERS_RHSADEMO = {"
for OPENSHIFT_USER_RHSADEMO in ${!OPENSHIFT_USERS_RHSADEMO[@]}; do
	echo -n "	${OPENSHIFT_USERS_RHSADEMO[OPENSHIFT_USERS_RHSADEMO]} : "
	OPENSHIFT_USER_RHSADEMO_USERNAME_REF=${OPENSHIFT_USERS_RHSADEMO[$OPENSHIFT_USER_RHSADEMO]}[0] && echo -n "( username = ${!OPENSHIFT_USER_RHSADEMO_USERNAME_REF} ,  "
	OPENSHIFT_USER_RHSADEMO_PASSWORD_REF=${OPENSHIFT_USERS_RHSADEMO[$OPENSHIFT_USER_RHSADEMO]}[1] && echo -n "password = ` echo ${!OPENSHIFT_USER_RHSADEMO_PASSWORD_REF} | md5sum` (obfuscated) ,  "
	OPENSHIFT_USER_RHSADEMO_PROJECT_REF=${OPENSHIFT_USERS_RHSADEMO[$OPENSHIFT_USER_RHSADEMO]}[2] && echo -n "project = ${!OPENSHIFT_USER_RHSADEMO_PROJECT_REF} )"
	echo "" 
done
echo "}"

echo "____________________________________________________________"

CONFIGURATION_COMPLETED=true
